<?php

/**
 * @file
 * Hook implementation code for the Rate module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Url;
use Drupal\Core\Link;
use Drupal\rate\RateEntityVoteTotals;

// @Todo: implement permissions/has voted.
// @Todo add closed and extra info.

/**
 * Implements hook_entity_load().
 */
function rate_entity_load(array $entities, $entity_type_id) {
  $config = \Drupal::config('rate.settings');
  $vote_result_storage = \Drupal::entityTypeManager()->getStorage('vote_result');

  foreach ($entities as $entity) {
    $config_id = $entity->getEntityTypeId() . '_' . $entity->bundle() . '_available';
    if ($config->get($config_id, FALSE)) {
      if ($config->get('widget_type') == 'fivestar') {
        for ($counter = 1; $counter < 6; $counter++) {
          $star = $vote_result_storage->getEntityResults(
            $entity_type_id, $entity->id(), 'star' . $counter, 'vote_count'
          );
          $entity->{'star' . $counter} = !empty($star) ? current($star)->getValue() : 0;
        }
      }
      else {
        $up = $vote_result_storage->getEntityResults(
          $entity_type_id, $entity->id(), 'up', 'vote_count'
        );
        $entity->up = !empty($up) ? current($up)->getValue() : 0;
        $down = $vote_result_storage->getEntityResults(
          $entity_type_id, $entity->id(), 'down', 'vote_count'
        );
        $entity->down = !empty($down) ? current($down)->getValue() : 0;
      }
    }
  }
}

/**
 * Implements hook_entity_view().
 */
function rate_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $rate_totals = new RateEntityVoteTotals($entity);
  $rate_totals_output = $rate_totals->getEntityVoteTotals();
  $build = array_merge($build, $rate_totals_output);
}

/**
 * Implements hook_theme().
 */
function rate_theme($existing, $type, $theme, $path) {
  return array(
    // Templates for default widget types.
    'rate_template_thumbs_up' => array(
      'variables' => [
        'up_votes' => 0,
        'use_ajax' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-thumbs-up',
    ),
    'rate_template_thumbs_up_down' => array(
      'variables' => [
        'up_votes' => 0,
        'down_votes' => 0,
        'use_ajax' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-thumbs-up-down',
    ),
    'rate_template_number_up_down' => [
      'variables' => [
        'up_votes' => 0,
        'down_votes' => 0,
        'use_ajax' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-number-up-down',
    ],
    'rate_template_fivestar' => array(
      'variables' => [
        'star1_votes' => 0,
        'star2_votes' => 0,
        'star3_votes' => 0,
        'star4_votes' => 0,
        'star5_votes' => 0,
        'use_ajax' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-fivestar',
    ),
    'rate_template_yesno' => array(
      'variables' => [
        'up_votes' => 0,
        'down_votes' => 0,
        'use_ajax' => FALSE,
        'entity_id' => NULL,
        'entity_type_id' => NULL,
      ],
      'template' => 'rate-template-yesno',
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for rate-template-number-up-down.html.twig.
 */
function template_preprocess_rate_template_number_up_down(&$variables) {
  $up_class = 'rate-number-up-down-btn-up';
  if ($variables['use_ajax']) {
    $up_class .= ' use-ajax';
  }
  $up_item = Link::fromTextAndUrl(
    'Up',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'up',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => $up_class],
    ])
  );
  $variables['up_button'] = $up_item;

  $down_class = 'rate-number-up-down-btn-down';
  if ($variables['use_ajax']) {
    $down_class .= ' use-ajax';
  }
  $down_item = Link::fromTextAndUrl(
    'Down',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'down',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => $down_class],
    ])
  );
  $variables['down_button'] = $down_item;

  $score = $variables['up_votes'] - $variables['down_votes'];
  if ($score > 0) {
    $score = '+' . $score;
    $score_class = 'positive';
  }
  elseif ($score < 0) {
    $score = $score;
    $score_class = 'negative';
  }
  else {
    $score_class = 'neutral';
  }
  $variables['score'] = $score;
  $variables['score_class'] = $score_class;

  // @Todo add closed and extra info.

  $variables['#attached']['library'][] = 'rate/number-up-down';
}

/**
 * Implements hook_preprocess_HOOK() for rate-template-fivestar.html.twig.
 */
function template_preprocess_rate_template_fivestar(&$variables) {
  $stars = [];
  // Calculate the score.
  $score = 0;
  $total_votes = 0;
  for ($counter = 1; $counter < 6; $counter++) {
    $score += ($variables['star' . $counter . '_votes'] * $counter);
    $total_votes += $variables['star' . $counter . '_votes'];
  }
  $score = round($score / $total_votes);

  // Set up the links.
  for ($counter = 1; $counter < 6; $counter++) {
    if ($counter <= $score) {
      $class = 'rate-fivestar-btn-filled';
    }
    else {
      $class = 'rate-fivestar-btn-empty';
    }
    $class .= ' rate-fivestar-' . ($counter + 1);
    $stars[] = Link::fromTextAndUrl(
      'Stars ' . $counter,
      Url::fromRoute('rate.vote', [
        'entity_type_id' => $variables['entity_type_id'],
        'vote_type_id' => 'star' . $counter,
        'entity_id' => $variables['entity_id'],
        'destination' => drupal_get_destination()['destination'],
      ], [
        'attributes' => ['class' => $class],
      ])
    );
  }

  $variables['stars'] = [
    '#theme' => 'item_list',
    '#items' => $stars,
  ];

  $variables['#attached']['library'][] = 'rate/fivestar';
}

/**
 * Implements hook_preprocess_HOOK() for rate-template-thumbs_up_down.html.twig.
 */
function template_preprocess_rate_template_thumbs_up_down(&$variables) {
  $up_item = Link::fromTextAndUrl(
    'Up',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'up',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => 'rate-thumbs-up-down-btn-up'],
    ])
  );
  $variables['up_button'] = $up_item;

  $down_item = Link::fromTextAndUrl(
    'Down',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'down',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => 'rate-thumbs-up-down-btn-down'],
    ])
  );
  $variables['down_button'] = $down_item;

  $total_votes = $variables['up_votes'] + $variables['down_votes'];
  $variables['up_percent'] = round(($variables['up_votes'] / $total_votes) * 100);
  $variables['down_percent'] = round(($variables['down_votes'] / $total_votes) * 100);
  $variables['#attached']['library'][] = 'rate/thumbs-up-down';
}

/**
 * Implements hook_preprocess_HOOK() for rate-template-thumbs_up.html.twig.
 */
function template_preprocess_rate_template_thumbs_up(&$variables) {
  $up_item = Link::fromTextAndUrl(
    'Up',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'up',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => 'rate-thumbs-up-btn-up'],
    ])
  );
  $variables['up_button'] = $up_item;
  $variables['#attached']['library'][] = 'rate/thumbs-up';
}

/**
 * Implements hook_preprocess_HOOK() for rate-template-yes_no.html.twig.
 */
function template_preprocess_rate_template_yesno(&$variables) {
  $buttons = [];

  $up_item = Link::fromTextAndUrl(
    'Yes',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'up',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => 'rate-yesno-btn rate-yes-btn'],
    ])
  );
  $variables['yes_button'] = $up_item;

  $down_item = Link::fromTextAndUrl(
    'No',
    Url::fromRoute('rate.vote', [
      'entity_type_id' => $variables['entity_type_id'],
      'vote_type_id' => 'down',
      'entity_id' => $variables['entity_id'],
      'destination' => drupal_get_destination()['destination'],
    ], [
      'attributes' => ['class' => 'rate-yesno-btn rate-no-btn'],
    ])
  );
  $variables['no_button'] = $down_item;

  $variables['#attached']['library'][] = 'rate/yesno';
}
