<?php

/**
 * @file
 * Hook implementation code for the Rate module.
 */

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use \Drupal\Core\Url;

/**
 * Implements hook_entity_load().
 */
function rate_entity_load(array $entities, $entity_type_id) {
  $config = \Drupal::config('rate.settings');
  $vote_result_storage = \Drupal::entityTypeManager()->getStorage('vote_result');

  foreach ($entities as $entity) {
    $config_id = $entity->getEntityTypeId() . '_' . $entity->bundle() . '_available';
    if ($config->get($config_id, FALSE)) {
      $like = $vote_result_storage->getEntityResults(
        $entity_type_id, $entity->id(), 'like', 'vote_count'
      );
      $entity->like = !empty($like) ? current($like)->getValue() : 0;
      $dislike = $vote_result_storage->getEntityResults(
        $entity_type_id, $entity->id(), 'dislike', 'vote_count'
      );
      $entity->dislike = !empty($dislike) ? current($dislike)->getValue() : 0;
    }
  }
}

/**
 * Implements hook_entity_view().
 */
function rate_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $config = \Drupal::config('rate.settings');
  $enabled_view_modes = ['full'];
  $config_id = $entity->getEntityTypeId() . '_' . $entity->bundle() . '_available';

  // $entity_type_ids_available_to_vote = \Drupal\like_and_dislike\LikeDislikePermissions::getEntityTypesAvailableToVote();

  $account = \Drupal::currentUser();

  if ($config->get($config_id, FALSE) && in_array($view_mode, $enabled_view_modes)) {
    $entity_type_id = $entity->getEntityTypeId();
    $links = [];
    if (TRUE) {
      $like_item = \Drupal\Core\Link::fromTextAndUrl(
        $entity->like . ' Like',
        Url::fromRoute('rate.vote', [
          'entity_type_id' => $entity->getEntityTypeId(),
          'vote_type_id' => 'like',
          'entity_id' => $entity->id(),
          'destination' => drupal_get_destination()['destination']
        ])
      );
    }
    else {
      $like_item = $entity->like . ' Like';
    }
    $links['like'] = $like_item;
    if ($account->hasPermission("add or remove like votes on $entity_type_id")) {
      $dislike_item = \Drupal\Core\Link::fromTextAndUrl(
        $entity->dislike . ' Dislike',
        Url::fromRoute('rate.vote', [
          'entity_type_id' => $entity->getEntityTypeId(),
          'vote_type_id' => 'dislike',
          'entity_id' => $entity->id(),
          'destination' => drupal_get_destination()['destination']
        ])
      );
    }
    else {
      $dislike_item = $entity->dislike . ' Dislike';
    }
    $links['dislike'] = $dislike_item;

    $build['votingapi_links'] = array(
      '#theme' => 'item_list__votingapi',
      '#items' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
    );
  }
}

/**
 *
 */
function rate_vote_insert(EntityInterface $vote) {
  switch ($vote->bundle()) {
    case 'like':
      $vote_type_to_delete = 'dislike';
      break;
    case 'dislike':
      $vote_type_to_delete = 'like';
      break;
  }
  $vote_storage = \Drupal::entityTypeManager()->getStorage('vote');
  $vote_storage->deleteUserVotes(
    $vote->getOwnerId(),
    $vote_type_to_delete,
    $vote->getVotedEntityType(),
    $vote->getVotedEntityId()
  );
}

/**
 * Implements hook_theme().
 */
function rate_theme() {
  return array(
    'rate_widget' => array(
      'pattern' => 'rate_widget__',
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-widget',
    ),
    'rate_button' => array(
      'pattern' => 'rate_button__',
      'variables' => array('text' => NULL, 'href' => NULL, 'class' => NULL),
    ),
    // Templates for default widget types.
    'rate_template_thumbs_up' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-thumbs-up',
      'path' => drupal_get_path('module', 'rate') . '/templates/thumbs-up',
    ),
    'rate_template_thumbs_up_down' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-thumbs-up-down',
      'path' => drupal_get_path('module', 'rate') . '/templates/thumbs-up-down',
    ),
    'rate_template_number_up_down' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-number-up-down',
      'path' => drupal_get_path('module', 'rate') . '/templates/number-up-down',
    ),
    'rate_template_fivestar' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-fivestar',
      'path' => drupal_get_path('module', 'rate') . '/templates/fivestar',
    ),
    'rate_template_emotion' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-emotion',
      'path' => drupal_get_path('module', 'rate') . '/templates/emotion',
    ),
    'rate_template_yesno' => array(
      'variables' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL, 'display_options' => NULL),
      'template' => 'rate-template-yesno',
      'path' => drupal_get_path('module', 'rate') . '/templates/yesno',
    ),
  );
}

/**
 * Theme rate button.
 *
 * @param array $variables
 * @return string
 */
function theme_rate_button($variables) {
  $text = $variables['text'];
  $href = $variables['href'];
  $class = $variables['class'];
  static $id = 0;
  $id++;

  $classes = 'rate-button';
  if ($class) {
    $classes .= ' ' . $class;
  }
  if (empty($href)) {
    // Widget is disabled or closed.
    return '<span class="' . $classes . '" id="rate-button-' . $id . '">' .
      \Drupal\Component\Utility\Html::escape($text) .
      '</span>';
  }
  else {
    return '<a class="' . $classes . '" id="rate-button-' . $id . '" rel="nofollow" href="' . htmlentities($href) . '" title="' . \Drupal\Component\Utility\Html::escape($text) . '">' .
      \Drupal\Component\Utility\Html::escape($text) .
      '</a>';
  }
}
